### ISSUE TITLE
Sorting slow

### ISSUE THREAD

**Issue by 5thHorseman** [appuns/DSPAutoSorter#1]
I'm not sure if it's the new AutoSorter update or the new Dyson Sphere update, but auto sorter is "slow" in sorting my inventory now. There used to be such a small delay I didn't know there was a delay, and now it seems to take multiple seconds or more to sort, enough time for me to click the "sort" button to sort. I did not change my configs or reinstall.

**Comment by appuns** [comment]
I can't see it in my game.
sort is slow without mod?

**Comment by 5thHorseman** [comment]
Like my other reported problem, this one went away after a day.

I never tried sorting without the mod enabled, so can't say if that would have been slow as well.

This may be closed.
