### ISSUE TITLE
Sort fuel set to False, still sorting fuel

### ISSUE THREAD

**Issue by 5thHorseman** [appuns/DSPAutoSorter#2]
This issue is new in the newest version. I have and have had fuel set to not sort, and in previous versions it did not. In this version, it is sorting fuel now.

**Comment by appuns** [comment]
there is a option "enableSortInFuelChamber" .
enableSortInFuelChamber is false?

**Comment by 5thHorseman** [comment]
Sorry, I failed to come back and check for questions.
This can be closed. I don't know what was wrong but it's fine now. All I DO know is that for a day or so, enableSortInFuelChamber was false and it was sorting fuel. But right after I reported this, the next day it was fine. I figured you'd fixed it :)
