### ISSUE TITLE
Control & Shift Clicking Behavior Bug

### ISSUE THREAD

**Issue by dpthorngren** [appuns/DSPAutoSorter#3]
- Game Version: 9.24.11286 (current)
- DSPAutoSorter Version: 1.2.5 (current)
- Mod Config: All options default (set to true), including ForcedSort.
- Mods Installed: BepInEx and DSPAutoSorter only.

When the control or shift keys are held down, items can be moved without triggering a sort.  Shift-clicking correctly transfers one item stack to another container, and control-clicking correctly transfers all items of that type, but neither container is sorted.   If an item is control-clicked without another container open, only some of the item stacks of that type are picked up (in vanilla DSP, all of that type are picked up).  If neither control nor shift are used, the mod works as expected.

I tried to figure out what the problem was by adding the UnityExplorer mod.  Calling `UIStorageGrid.HandPut(...)` correctly triggers a sort.  Maybe a recent patch changed how control- or shift-clicking transfers are handled?

Also, thank you for making this mod; I find it very helpful!

**Comment by appuns** [comment]
Thank you for reporting!
I tried to improve it.
How about this?
https://dsp.thunderstore.io/package/appuns/DSPAutoSorter/

**Comment by dpthorngren** [comment]
I just tried it and it works perfectly!  Thank you; I'm amazed by the quick work!
